//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAboutSection
    {
        public int Id { get; set; }
        public string Name_Surname { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Section { get; set; }
    }
}
