//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeature
    {
        public int FeatureID { get; set; }
        public string FetaureTitle { get; set; }
        public string FeatureDescrition { get; set; }
        public string FeatureImageURL { get; set; }
    }
}
