//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSkillsAbout
    {
        public int SkillIAboutd { get; set; }
        public string SkillAboutName { get; set; }
        public Nullable<int> Ratio { get; set; }
    }
}
